services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  weaviate:
    image: semitechnologies/weaviate
    ports:
      - 8080:8080
      - 50051:50051 
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    build: 
      dockerfile: docker/ollama.dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    runtime: nvidia

  postgres:
    image: postgres:bullseye
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: gus
      POSTGRES_PASSWORD: gus
    command: >
      postgres
        -c shared_buffers=8GB
        -c work_mem=1024MB
        -c maintenance_work_mem=6GB
        -c effective_cache_size=20GB
        -c random_page_cost=1.1
        -c max_worker_processes=16
        -c max_parallel_workers=16
        -c max_parallel_workers_per_gather=8
        -c checkpoint_completion_target=0.9
        -c max_wal_size=16GB
        -c default_statistics_target=200
    deploy:
      resources:
        limits:
          cpus: '12'  # Ajuste conforme número de cores do seu i9
          memory: 28G
        reservations:
          memory: 16G

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 43200
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - postgres:postgres
    depends_on:
      - postgres

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: gus
      MONGO_INITDB_ROOT_PASSWORD: gus

volumes:
  n8n_data:
  weaviate_data:
  ollama_data:
  postgres_data:
  redis_data:
  pgadmin_data:
  mongodb_data: