services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  weaviate:
    image: semitechnologies/weaviate:1.28.8
    ports:
      - 8080:8080
      - 50051:50051 
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama/ollama:0.5.12
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      #OLLAMA_MODELS: deepseek-r1:8b
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    runtime: nvidia

volumes:
  n8n_data:
  weaviate_data:
  ollama_data: